# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='host',
            name='host_name',
        ),
    ]
